[
  (class_declaration)
  (struct_declaration)
  (interface_declaration)
  (enum_declaration)
  (record_declaration)
  (namespace_declaration)
  (method_declaration)
  (constructor_declaration)
  (destructor_declaration)
  (property_declaration)
  (local_function_statement)
  (if_statement)
  (for_statement)
  (for_each_statement)
  (while_statement)
  (do_statement)
  (switch_statement)
  (try_statement)
  (using_statement)
  (lock_statement)
  (block)
  (comment)
] @fold

